# Generated by Django 3.0.7 on 2020-11-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=30)),
                ('sitePhone', models.IntegerField()),
                ('siteLogo', models.ImageField(blank=True, upload_to='siteImages/')),
                ('siteEmail', models.EmailField(max_length=254)),
                ('siteAddress', models.CharField(max_length=250)),
                ('siteAbout', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('contact_page_banner', models.ImageField(blank=True, upload_to='siteImages/contact_page_banner')),
            ],
        ),
    ]
