# Generated by Django 3.0.7 on 2020-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201101_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_img',
            field=models.ImageField(default='cover.png', upload_to='cover_pics'),
        ),
    ]
