# Generated by Django 3.0.7 on 2020-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201102_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_img',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profile_pics'),
        ),
    ]
