# Generated by Django 3.0.7 on 2020-11-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComapanyImages',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
                ('company_image', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='company_images')),
            ],
        ),
    ]
