# Generated by Django 3.0.7 on 2020-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201127_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institute_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
