# Generated by Django 3.0.7 on 2020-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201127_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog-default.jpg', upload_to='blog_pics'),
        ),
    ]
