# Generated by Django 3.0.7 on 2020-10-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20201101_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job Categories'},
        ),
    ]
