# Generated by Django 3.0.7 on 2020-11-03 15:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_auto_20201101_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(default='Write Your Content Here'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Paid'), ('2', 'Unpaid')], max_length=10),
        ),
    ]
