# Generated by Django 3.0.7 on 2020-11-03 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_auto_20201103_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='Write Your Content Here', null=True),
        ),
    ]
