# Generated by Django 3.0.7 on 2020-11-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_auto_20201103_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='logo',
            field=models.ImageField(blank=True, default='default_cat.png', null=True, upload_to='cat_pics'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
