# Generated by Django 3.0.7 on 2020-11-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Selected'), ('2', 'Rejected')], max_length=30, null=True),
        ),
    ]
