# Generated by Django 3.0.7 on 2020-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0017_auto_20201118_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
