# Generated by Django 3.0.7 on 2020-11-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0018_job_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
    ]
