# Generated by Django 3.0.7 on 2020-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0019_auto_20201125_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('1', 'Selected'), ('2', 'Rejected')], default=0, max_length=30),
        ),
    ]
