# Generated by Django 3.0.7 on 2020-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_auto_20201129_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('n/a', 'N/A'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='n/a', max_length=6),
        ),
    ]
