# Generated by Django 3.0.7 on 2020-12-13 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0025_auto_20201213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
